from wordmarker.loaders.default_resource_loader import DefaultResourceLoader
from wordmarker.loaders.yaml_resource_loader import YamlResourceLoader
from wordmarker.loaders.xml_resource_loader import XmlResourceLoader
